// Generated by CIRCT firtool-1.62.1
module ParallelGaloisLFSR(
  input         clock,
                reset,
                io_resetLfsr,
                io_increment,
  output [31:0] io_lfsrOutput,
  output [22:0] io_state
);

  wire        io_resetLfsr_0 = io_resetLfsr;
  wire        io_increment_0 = io_increment;
  wire [31:0] io_lfsrOutput_0;
  wire [22:0] io_state_0;
  reg  [22:0] stateReg;
  assign io_state_0 = stateReg;
  wire        stateUpdateWire_0;
  wire        stateUpdateWire_1;
  wire        stateUpdateWire_2;
  wire        stateUpdateWire_3;
  wire        stateUpdateWire_4;
  wire        stateUpdateWire_5;
  wire        stateUpdateWire_6;
  wire        stateUpdateWire_7;
  wire        stateUpdateWire_8;
  wire        stateUpdateWire_9;
  wire        stateUpdateWire_10;
  wire        stateUpdateWire_11;
  wire        stateUpdateWire_12;
  wire        stateUpdateWire_13;
  wire        stateUpdateWire_14;
  wire        stateUpdateWire_15;
  wire        stateUpdateWire_16;
  wire        stateUpdateWire_17;
  wire        stateUpdateWire_18;
  wire        stateUpdateWire_19;
  wire        stateUpdateWire_20;
  wire        stateUpdateWire_21;
  wire        stateUpdateWire_22;
  wire        dataOutputWire_0;
  wire        dataOutputWire_1;
  wire        dataOutputWire_2;
  wire        dataOutputWire_3;
  wire        dataOutputWire_4;
  wire        dataOutputWire_5;
  wire        dataOutputWire_6;
  wire        dataOutputWire_7;
  wire        dataOutputWire_8;
  wire        dataOutputWire_9;
  wire        dataOutputWire_10;
  wire        dataOutputWire_11;
  wire        dataOutputWire_12;
  wire        dataOutputWire_13;
  wire        dataOutputWire_14;
  wire        dataOutputWire_15;
  wire        dataOutputWire_16;
  wire        dataOutputWire_17;
  wire        dataOutputWire_18;
  wire        dataOutputWire_19;
  wire        dataOutputWire_20;
  wire        dataOutputWire_21;
  wire        dataOutputWire_22;
  wire        dataOutputWire_23;
  wire        dataOutputWire_24;
  wire        dataOutputWire_25;
  wire        dataOutputWire_26;
  wire        dataOutputWire_27;
  wire        dataOutputWire_28;
  wire        dataOutputWire_29;
  wire        dataOutputWire_30;
  wire        dataOutputWire_31;
  assign dataOutputWire_1 = stateReg[21];
  assign dataOutputWire_0 = stateReg[22];
  assign stateUpdateWire_22 =
    stateReg[0] ^ stateReg[1] ^ stateReg[2] ^ stateReg[10] ^ stateReg[12] ^ stateReg[13]
    ^ stateReg[15] ^ stateReg[17] ^ stateReg[19] ^ stateReg[20] ^ dataOutputWire_1
    ^ dataOutputWire_0;
  assign stateUpdateWire_21 =
    stateReg[0] ^ stateReg[1] ^ stateReg[9] ^ stateReg[11] ^ stateReg[12] ^ stateReg[14]
    ^ stateReg[16] ^ stateReg[18] ^ stateReg[19] ^ stateReg[20] ^ dataOutputWire_1
    ^ dataOutputWire_0;
  assign stateUpdateWire_20 =
    stateReg[1] ^ stateReg[2] ^ stateReg[8] ^ stateReg[11] ^ stateReg[12] ^ stateReg[18];
  assign stateUpdateWire_19 =
    stateReg[0] ^ stateReg[1] ^ stateReg[7] ^ stateReg[10] ^ stateReg[11] ^ stateReg[17];
  assign stateUpdateWire_18 =
    stateReg[0] ^ stateReg[6] ^ stateReg[9] ^ stateReg[10] ^ stateReg[16]
    ^ dataOutputWire_0;
  assign stateUpdateWire_17 =
    stateReg[5] ^ stateReg[8] ^ stateReg[9] ^ stateReg[15] ^ dataOutputWire_1;
  assign stateUpdateWire_16 =
    stateReg[4] ^ stateReg[7] ^ stateReg[8] ^ stateReg[14] ^ stateReg[20]
    ^ dataOutputWire_0;
  assign stateUpdateWire_15 =
    stateReg[0] ^ stateReg[1] ^ stateReg[2] ^ stateReg[3] ^ stateReg[6] ^ stateReg[7]
    ^ stateReg[10] ^ stateReg[12] ^ stateReg[15] ^ stateReg[17] ^ stateReg[20];
  assign stateUpdateWire_14 =
    stateReg[0] ^ stateReg[1] ^ stateReg[2] ^ stateReg[5] ^ stateReg[6] ^ stateReg[9]
    ^ stateReg[11] ^ stateReg[14] ^ stateReg[16] ^ stateReg[19];
  assign stateUpdateWire_13 =
    stateReg[0] ^ stateReg[1] ^ stateReg[4] ^ stateReg[5] ^ stateReg[8] ^ stateReg[10]
    ^ stateReg[13] ^ stateReg[15] ^ stateReg[18];
  assign stateUpdateWire_12 =
    stateReg[0] ^ stateReg[3] ^ stateReg[4] ^ stateReg[7] ^ stateReg[9] ^ stateReg[12]
    ^ stateReg[14] ^ stateReg[17] ^ dataOutputWire_0;
  assign stateUpdateWire_11 =
    stateReg[2] ^ stateReg[3] ^ stateReg[6] ^ stateReg[8] ^ stateReg[11] ^ stateReg[13]
    ^ stateReg[16] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign stateUpdateWire_10 =
    stateReg[1] ^ stateReg[2] ^ stateReg[5] ^ stateReg[7] ^ stateReg[10] ^ stateReg[12]
    ^ stateReg[15] ^ stateReg[20] ^ dataOutputWire_1;
  assign stateUpdateWire_9 =
    stateReg[0] ^ stateReg[1] ^ stateReg[4] ^ stateReg[6] ^ stateReg[9] ^ stateReg[11]
    ^ stateReg[14] ^ stateReg[19] ^ stateReg[20] ^ dataOutputWire_0;
  assign stateUpdateWire_8 =
    stateReg[0] ^ stateReg[3] ^ stateReg[5] ^ stateReg[8] ^ stateReg[10] ^ stateReg[13]
    ^ stateReg[18] ^ stateReg[19] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign stateUpdateWire_7 =
    stateReg[0] ^ stateReg[1] ^ stateReg[4] ^ stateReg[7] ^ stateReg[9] ^ stateReg[10]
    ^ stateReg[13] ^ stateReg[15] ^ stateReg[18] ^ stateReg[19] ^ dataOutputWire_0;
  assign stateUpdateWire_6 =
    stateReg[0] ^ stateReg[3] ^ stateReg[6] ^ stateReg[8] ^ stateReg[9] ^ stateReg[12]
    ^ stateReg[14] ^ stateReg[17] ^ stateReg[18] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign stateUpdateWire_5 =
    stateReg[2] ^ stateReg[5] ^ stateReg[7] ^ stateReg[8] ^ stateReg[11] ^ stateReg[13]
    ^ stateReg[16] ^ stateReg[17] ^ stateReg[20] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign stateUpdateWire_4 =
    stateReg[0] ^ stateReg[2] ^ stateReg[4] ^ stateReg[6] ^ stateReg[7] ^ stateReg[13]
    ^ stateReg[16] ^ stateReg[17];
  assign stateUpdateWire_3 =
    stateReg[1] ^ stateReg[3] ^ stateReg[5] ^ stateReg[6] ^ stateReg[12] ^ stateReg[15]
    ^ stateReg[16] ^ dataOutputWire_0;
  assign stateUpdateWire_2 =
    stateReg[0] ^ stateReg[2] ^ stateReg[4] ^ stateReg[5] ^ stateReg[11] ^ stateReg[14]
    ^ stateReg[15] ^ dataOutputWire_1;
  assign stateUpdateWire_1 =
    stateReg[0] ^ stateReg[2] ^ stateReg[3] ^ stateReg[4] ^ stateReg[12] ^ stateReg[14]
    ^ stateReg[15] ^ stateReg[17] ^ stateReg[19] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign stateUpdateWire_0 =
    stateReg[1] ^ stateReg[2] ^ stateReg[3] ^ stateReg[11] ^ stateReg[13] ^ stateReg[14]
    ^ stateReg[16] ^ stateReg[18] ^ stateReg[20] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign dataOutputWire_31 =
    stateReg[1] ^ stateReg[2] ^ stateReg[3] ^ stateReg[11] ^ stateReg[13] ^ stateReg[14]
    ^ stateReg[16] ^ stateReg[18] ^ stateReg[20] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign dataOutputWire_30 =
    stateReg[0] ^ stateReg[2] ^ stateReg[3] ^ stateReg[4] ^ stateReg[12] ^ stateReg[14]
    ^ stateReg[15] ^ stateReg[17] ^ stateReg[19] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign dataOutputWire_29 =
    stateReg[0] ^ stateReg[1] ^ stateReg[3] ^ stateReg[4] ^ stateReg[5] ^ stateReg[13]
    ^ stateReg[15] ^ stateReg[16] ^ stateReg[18] ^ stateReg[20] ^ dataOutputWire_0;
  assign dataOutputWire_28 =
    stateReg[0] ^ stateReg[1] ^ stateReg[2] ^ stateReg[4] ^ stateReg[5] ^ stateReg[6]
    ^ stateReg[14] ^ stateReg[16] ^ stateReg[17] ^ stateReg[19] ^ dataOutputWire_1;
  assign dataOutputWire_27 =
    stateReg[1] ^ stateReg[2] ^ stateReg[3] ^ stateReg[5] ^ stateReg[6] ^ stateReg[7]
    ^ stateReg[15] ^ stateReg[17] ^ stateReg[18] ^ stateReg[20] ^ dataOutputWire_0;
  assign dataOutputWire_26 =
    stateReg[0] ^ stateReg[2] ^ stateReg[3] ^ stateReg[4] ^ stateReg[6] ^ stateReg[7]
    ^ stateReg[8] ^ stateReg[16] ^ stateReg[18] ^ stateReg[19] ^ dataOutputWire_1;
  assign dataOutputWire_25 =
    stateReg[1] ^ stateReg[3] ^ stateReg[4] ^ stateReg[5] ^ stateReg[7] ^ stateReg[8]
    ^ stateReg[9] ^ stateReg[17] ^ stateReg[19] ^ stateReg[20] ^ dataOutputWire_0;
  assign dataOutputWire_24 =
    stateReg[0] ^ stateReg[2] ^ stateReg[4] ^ stateReg[5] ^ stateReg[6] ^ stateReg[8]
    ^ stateReg[9] ^ stateReg[10] ^ stateReg[18] ^ stateReg[20] ^ dataOutputWire_1;
  assign dataOutputWire_23 =
    stateReg[1] ^ stateReg[3] ^ stateReg[5] ^ stateReg[6] ^ stateReg[7] ^ stateReg[9]
    ^ stateReg[10] ^ stateReg[11] ^ stateReg[19] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign dataOutputWire_22 =
    stateReg[0] ^ stateReg[2] ^ stateReg[4] ^ stateReg[6] ^ stateReg[7] ^ stateReg[8]
    ^ stateReg[10] ^ stateReg[11] ^ stateReg[12] ^ stateReg[20] ^ dataOutputWire_0;
  assign dataOutputWire_21 =
    stateReg[1] ^ stateReg[3] ^ stateReg[5] ^ stateReg[7] ^ stateReg[8] ^ stateReg[9]
    ^ stateReg[11] ^ stateReg[12] ^ stateReg[13] ^ dataOutputWire_1;
  assign dataOutputWire_20 =
    stateReg[2] ^ stateReg[4] ^ stateReg[6] ^ stateReg[8] ^ stateReg[9] ^ stateReg[10]
    ^ stateReg[12] ^ stateReg[13] ^ stateReg[14] ^ dataOutputWire_0;
  assign dataOutputWire_19 =
    stateReg[3] ^ stateReg[5] ^ stateReg[7] ^ stateReg[9] ^ stateReg[10] ^ stateReg[11]
    ^ stateReg[13] ^ stateReg[14] ^ stateReg[15];
  assign dataOutputWire_18 =
    stateReg[4] ^ stateReg[6] ^ stateReg[8] ^ stateReg[10] ^ stateReg[11] ^ stateReg[12]
    ^ stateReg[14] ^ stateReg[15] ^ stateReg[16];
  assign dataOutputWire_17 =
    stateReg[5] ^ stateReg[7] ^ stateReg[9] ^ stateReg[11] ^ stateReg[12] ^ stateReg[13]
    ^ stateReg[15] ^ stateReg[16] ^ stateReg[17];
  assign dataOutputWire_16 =
    stateReg[6] ^ stateReg[8] ^ stateReg[10] ^ stateReg[12] ^ stateReg[13] ^ stateReg[14]
    ^ stateReg[16] ^ stateReg[17] ^ stateReg[18];
  assign dataOutputWire_15 =
    stateReg[7] ^ stateReg[9] ^ stateReg[11] ^ stateReg[13] ^ stateReg[14] ^ stateReg[15]
    ^ stateReg[17] ^ stateReg[18] ^ stateReg[19];
  assign dataOutputWire_14 =
    stateReg[8] ^ stateReg[10] ^ stateReg[12] ^ stateReg[14] ^ stateReg[15] ^ stateReg[16]
    ^ stateReg[18] ^ stateReg[19] ^ stateReg[20];
  assign dataOutputWire_13 =
    stateReg[9] ^ stateReg[11] ^ stateReg[13] ^ stateReg[15] ^ stateReg[16] ^ stateReg[17]
    ^ stateReg[19] ^ stateReg[20] ^ dataOutputWire_1;
  assign dataOutputWire_12 =
    stateReg[10] ^ stateReg[12] ^ stateReg[14] ^ stateReg[16] ^ stateReg[17]
    ^ stateReg[18] ^ stateReg[20] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign dataOutputWire_11 =
    stateReg[11] ^ stateReg[13] ^ stateReg[15] ^ stateReg[17] ^ stateReg[18]
    ^ stateReg[19] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign dataOutputWire_10 =
    stateReg[12] ^ stateReg[14] ^ stateReg[16] ^ stateReg[18] ^ stateReg[19]
    ^ stateReg[20] ^ dataOutputWire_0;
  assign dataOutputWire_9 =
    stateReg[13] ^ stateReg[15] ^ stateReg[17] ^ stateReg[19] ^ stateReg[20]
    ^ dataOutputWire_1;
  assign dataOutputWire_8 =
    stateReg[14] ^ stateReg[16] ^ stateReg[18] ^ stateReg[20] ^ dataOutputWire_1
    ^ dataOutputWire_0;
  assign dataOutputWire_7 =
    stateReg[15] ^ stateReg[17] ^ stateReg[19] ^ dataOutputWire_1 ^ dataOutputWire_0;
  assign dataOutputWire_6 = stateReg[16] ^ stateReg[18] ^ stateReg[20] ^ dataOutputWire_0;
  assign dataOutputWire_5 = stateReg[17] ^ stateReg[19] ^ dataOutputWire_1;
  assign dataOutputWire_4 = stateReg[18] ^ stateReg[20] ^ dataOutputWire_0;
  assign dataOutputWire_3 = stateReg[19] ^ dataOutputWire_1;
  assign dataOutputWire_2 = stateReg[20] ^ dataOutputWire_0;
  wire [1:0]  stateReg_lo_lo_lo = {stateUpdateWire_1, stateUpdateWire_0};
  wire [1:0]  stateReg_lo_lo_hi_hi = {stateUpdateWire_4, stateUpdateWire_3};
  wire [2:0]  stateReg_lo_lo_hi = {stateReg_lo_lo_hi_hi, stateUpdateWire_2};
  wire [4:0]  stateReg_lo_lo = {stateReg_lo_lo_hi, stateReg_lo_lo_lo};
  wire [1:0]  stateReg_lo_hi_lo_hi = {stateUpdateWire_7, stateUpdateWire_6};
  wire [2:0]  stateReg_lo_hi_lo = {stateReg_lo_hi_lo_hi, stateUpdateWire_5};
  wire [1:0]  stateReg_lo_hi_hi_hi = {stateUpdateWire_10, stateUpdateWire_9};
  wire [2:0]  stateReg_lo_hi_hi = {stateReg_lo_hi_hi_hi, stateUpdateWire_8};
  wire [5:0]  stateReg_lo_hi = {stateReg_lo_hi_hi, stateReg_lo_hi_lo};
  wire [10:0] stateReg_lo = {stateReg_lo_hi, stateReg_lo_lo};
  wire [1:0]  stateReg_hi_lo_lo_hi = {stateUpdateWire_13, stateUpdateWire_12};
  wire [2:0]  stateReg_hi_lo_lo = {stateReg_hi_lo_lo_hi, stateUpdateWire_11};
  wire [1:0]  stateReg_hi_lo_hi_hi = {stateUpdateWire_16, stateUpdateWire_15};
  wire [2:0]  stateReg_hi_lo_hi = {stateReg_hi_lo_hi_hi, stateUpdateWire_14};
  wire [5:0]  stateReg_hi_lo = {stateReg_hi_lo_hi, stateReg_hi_lo_lo};
  wire [1:0]  stateReg_hi_hi_lo_hi = {stateUpdateWire_19, stateUpdateWire_18};
  wire [2:0]  stateReg_hi_hi_lo = {stateReg_hi_hi_lo_hi, stateUpdateWire_17};
  wire [1:0]  stateReg_hi_hi_hi_hi = {stateUpdateWire_22, stateUpdateWire_21};
  wire [2:0]  stateReg_hi_hi_hi = {stateReg_hi_hi_hi_hi, stateUpdateWire_20};
  wire [5:0]  stateReg_hi_hi = {stateReg_hi_hi_hi, stateReg_hi_hi_lo};
  wire [11:0] stateReg_hi = {stateReg_hi_hi, stateReg_hi_lo};
  wire [1:0]  io_lfsrOutput_lo_lo_lo_lo = {dataOutputWire_1, dataOutputWire_0};
  wire [1:0]  io_lfsrOutput_lo_lo_lo_hi = {dataOutputWire_3, dataOutputWire_2};
  wire [3:0]  io_lfsrOutput_lo_lo_lo =
    {io_lfsrOutput_lo_lo_lo_hi, io_lfsrOutput_lo_lo_lo_lo};
  wire [1:0]  io_lfsrOutput_lo_lo_hi_lo = {dataOutputWire_5, dataOutputWire_4};
  wire [1:0]  io_lfsrOutput_lo_lo_hi_hi = {dataOutputWire_7, dataOutputWire_6};
  wire [3:0]  io_lfsrOutput_lo_lo_hi =
    {io_lfsrOutput_lo_lo_hi_hi, io_lfsrOutput_lo_lo_hi_lo};
  wire [7:0]  io_lfsrOutput_lo_lo = {io_lfsrOutput_lo_lo_hi, io_lfsrOutput_lo_lo_lo};
  wire [1:0]  io_lfsrOutput_lo_hi_lo_lo = {dataOutputWire_9, dataOutputWire_8};
  wire [1:0]  io_lfsrOutput_lo_hi_lo_hi = {dataOutputWire_11, dataOutputWire_10};
  wire [3:0]  io_lfsrOutput_lo_hi_lo =
    {io_lfsrOutput_lo_hi_lo_hi, io_lfsrOutput_lo_hi_lo_lo};
  wire [1:0]  io_lfsrOutput_lo_hi_hi_lo = {dataOutputWire_13, dataOutputWire_12};
  wire [1:0]  io_lfsrOutput_lo_hi_hi_hi = {dataOutputWire_15, dataOutputWire_14};
  wire [3:0]  io_lfsrOutput_lo_hi_hi =
    {io_lfsrOutput_lo_hi_hi_hi, io_lfsrOutput_lo_hi_hi_lo};
  wire [7:0]  io_lfsrOutput_lo_hi = {io_lfsrOutput_lo_hi_hi, io_lfsrOutput_lo_hi_lo};
  wire [15:0] io_lfsrOutput_lo = {io_lfsrOutput_lo_hi, io_lfsrOutput_lo_lo};
  wire [1:0]  io_lfsrOutput_hi_lo_lo_lo = {dataOutputWire_17, dataOutputWire_16};
  wire [1:0]  io_lfsrOutput_hi_lo_lo_hi = {dataOutputWire_19, dataOutputWire_18};
  wire [3:0]  io_lfsrOutput_hi_lo_lo =
    {io_lfsrOutput_hi_lo_lo_hi, io_lfsrOutput_hi_lo_lo_lo};
  wire [1:0]  io_lfsrOutput_hi_lo_hi_lo = {dataOutputWire_21, dataOutputWire_20};
  wire [1:0]  io_lfsrOutput_hi_lo_hi_hi = {dataOutputWire_23, dataOutputWire_22};
  wire [3:0]  io_lfsrOutput_hi_lo_hi =
    {io_lfsrOutput_hi_lo_hi_hi, io_lfsrOutput_hi_lo_hi_lo};
  wire [7:0]  io_lfsrOutput_hi_lo = {io_lfsrOutput_hi_lo_hi, io_lfsrOutput_hi_lo_lo};
  wire [1:0]  io_lfsrOutput_hi_hi_lo_lo = {dataOutputWire_25, dataOutputWire_24};
  wire [1:0]  io_lfsrOutput_hi_hi_lo_hi = {dataOutputWire_27, dataOutputWire_26};
  wire [3:0]  io_lfsrOutput_hi_hi_lo =
    {io_lfsrOutput_hi_hi_lo_hi, io_lfsrOutput_hi_hi_lo_lo};
  wire [1:0]  io_lfsrOutput_hi_hi_hi_lo = {dataOutputWire_29, dataOutputWire_28};
  wire [1:0]  io_lfsrOutput_hi_hi_hi_hi = {dataOutputWire_31, dataOutputWire_30};
  wire [3:0]  io_lfsrOutput_hi_hi_hi =
    {io_lfsrOutput_hi_hi_hi_hi, io_lfsrOutput_hi_hi_hi_lo};
  wire [7:0]  io_lfsrOutput_hi_hi = {io_lfsrOutput_hi_hi_hi, io_lfsrOutput_hi_hi_lo};
  wire [15:0] io_lfsrOutput_hi = {io_lfsrOutput_hi_hi, io_lfsrOutput_hi_lo};
  assign io_lfsrOutput_0 = {io_lfsrOutput_hi, io_lfsrOutput_lo};
  always @(posedge clock) begin
    if (reset | io_resetLfsr_0)
      stateReg <= 23'h1DBFBC;
    else if (io_increment_0)
      stateReg <= {stateReg_hi, stateReg_lo};
  end // always @(posedge)
  assign io_lfsrOutput = io_lfsrOutput_0;
  assign io_state = io_state_0;
endmodule

